[package]
name = "async-opcua-history-sqlite"
version = "0.19.0"
description = "OPC UA History Data Access (Part 11) SQLite backend"
authors = ["Adam Lock <locka99@gmail.com>", "Einar Omang <einar@omang.com>"]
license = "MPL-2.0"
edition = "2021"
publish = false

[lib]
name = "opcua_history_sqlite"

[dependencies]
async-opcua-core = { path = "../async-opcua-core", version = "0.19.0" }
async-opcua-types = { path = "../async-opcua-types", version = "0.19.0" }
async-opcua-server = { path = "../async-opcua-server", version = "0.19.0" }
tokio = { workspace = true }
tracing = { workspace = true }
rusqlite = { version = "0.31.0", features = ["bundled"] }
r2d2 = "0.8"
r2d2_sqlite = "0.24"
parking_lot = { workspace = true }
dashmap = "6.1"
async-trait = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
rusqlite = { version = "0.31.0", features = ["trace"] }

[lints]
workspace = true
