//! GDS pull model method callbacks.

use std::{collections::VecDeque, fmt, sync::Arc};

use opcua_core::sync::RwLock;
use opcua_crypto::{PrivateKey, X509};
use opcua_types::{
    Array, ByteString, MessageSecurityMode, NodeId, StatusCode, Variant, VariantScalarTypeId,
};

use crate::{
    node_manager::{memory::SimpleNodeManager, RequestContext},
    rbac::WellKnownRole,
};

use super::GDS_REGISTRY_CAPACITY;

const GET_REJECTED_LIST_METHOD_ID: u32 = 22407;
const UPDATE_CERTIFICATE_METHOD_ID: u32 = 22402;

/// Certificate material supplied by a GDS `UpdateCertificate` call.
#[derive(Clone, PartialEq, Eq)]
pub struct GdsCertificateUpdate {
    /// Certificate group selected for the update.
    pub certificate_group_id: NodeId,
    /// Certificate type selected for the update.
    pub certificate_type_id: NodeId,
    /// DER-encoded application certificate.
    pub certificate: ByteString,
    /// Optional issuer chain supplied with the certificate.
    pub issuer_certificates: Vec<ByteString>,
    /// Private key format, such as `PEM`, when a private key is supplied.
    pub private_key_format: String,
    /// Optional private key supplied by the GDS.
    pub private_key: ByteString,
}

impl fmt::Debug for GdsCertificateUpdate {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("GdsCertificateUpdate")
            .field("certificate_group_id", &self.certificate_group_id)
            .field("certificate_type_id", &self.certificate_type_id)
            .field("certificate", &RedactedByteString(&self.certificate))
            .field(
                "issuer_certificates",
                &RedactedByteStrings(&self.issuer_certificates),
            )
            .field("private_key_format", &self.private_key_format)
            .field("private_key", &RedactedByteString(&self.private_key))
            .finish()
    }
}

/// Certificate material returned by a GDS `FinishSigningRequest` call.
#[derive(Clone, PartialEq, Eq)]
pub struct GdsFinishedSigningRequest {
    /// Application whose signing request completed.
    pub application_id: NodeId,
    /// Request id returned by `StartSigningRequest`.
    pub request_id: NodeId,
    /// DER-encoded signed certificate.
    pub certificate: ByteString,
    /// Optional private key generated by the GDS.
    pub private_key: ByteString,
}

impl fmt::Debug for GdsFinishedSigningRequest {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("GdsFinishedSigningRequest")
            .field("application_id", &self.application_id)
            .field("request_id", &self.request_id)
            .field("certificate", &RedactedByteString(&self.certificate))
            .field("private_key", &RedactedByteString(&self.private_key))
            .finish()
    }
}

struct RedactedByteString<'a>(&'a ByteString);

impl fmt::Debug for RedactedByteString<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.0.is_null() {
            f.write_str("ByteString(<null>)")
        } else {
            write!(f, "ByteString(<redacted>; len={})", self.0.len())
        }
    }
}

struct RedactedByteStrings<'a>(&'a [ByteString]);

impl fmt::Debug for RedactedByteStrings<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let mut list = f.debug_list();
        for value in self.0 {
            list.entry(&RedactedByteString(value));
        }
        list.finish()
    }
}

#[derive(Default)]
struct GdsPullMethodRegistryInner {
    rejected_certificates: RwLock<VecDeque<ByteString>>,
    updated_certificates: RwLock<VecDeque<GdsCertificateUpdate>>,
    finished_signing_requests: RwLock<VecDeque<GdsFinishedSigningRequest>>,
}

/// In-memory registry for GDS pull certificate management state.
#[derive(Clone, Default)]
pub struct GdsPullMethodRegistry {
    inner: Arc<GdsPullMethodRegistryInner>,
}

impl GdsPullMethodRegistry {
    /// Records a certificate that should be returned by `GetRejectedList`.
    pub fn record_rejected_certificate(&self, certificate: ByteString) {
        push_bounded_fifo(&mut self.inner.rejected_certificates.write(), certificate);
    }

    /// Returns rejected certificates recorded for `GetRejectedList`.
    pub fn rejected_certificates(&self) -> Vec<ByteString> {
        self.inner
            .rejected_certificates
            .read()
            .iter()
            .cloned()
            .collect()
    }

    /// Returns certificate updates received through `UpdateCertificate`.
    pub fn updated_certificates(&self) -> Vec<GdsCertificateUpdate> {
        self.inner
            .updated_certificates
            .read()
            .iter()
            .cloned()
            .collect()
    }

    /// Records certificate material to return from `FinishSigningRequest`.
    pub fn record_finished_signing_request(
        &self,
        application_id: NodeId,
        request_id: NodeId,
        certificate: ByteString,
        private_key: ByteString,
    ) {
        let mut requests = self.inner.finished_signing_requests.write();
        push_bounded_fifo(
            &mut requests,
            GdsFinishedSigningRequest {
                application_id,
                request_id,
                certificate,
                private_key,
            },
        );
    }

    fn record_certificate_update(&self, update: GdsCertificateUpdate) {
        push_bounded_fifo(&mut self.inner.updated_certificates.write(), update);
    }

    fn finished_signing_request(
        &self,
        application_id: &NodeId,
        request_id: &NodeId,
    ) -> Option<GdsFinishedSigningRequest> {
        self.inner
            .finished_signing_requests
            .read()
            .iter()
            .find(|request| {
                &request.application_id == application_id && &request.request_id == request_id
            })
            .cloned()
    }
}

fn push_bounded_fifo<T>(items: &mut VecDeque<T>, item: T) {
    if items.len() >= GDS_REGISTRY_CAPACITY {
        items.pop_front();
    }
    items.push_back(item);
}

/// Handler for GDS pull model method calls.
pub struct GdsPullMethodHandler {
    registry: GdsPullMethodRegistry,
}

impl GdsPullMethodHandler {
    /// Creates a handler backed by the supplied in-memory registry.
    pub fn new(registry: GdsPullMethodRegistry) -> Self {
        Self { registry }
    }

    /// Handles `GetRejectedList` and returns a `ByteString[]` certificate list.
    pub fn handle_get_rejected_list(&self, args: &[Variant]) -> Result<Vec<Variant>, StatusCode> {
        self.handle_get_rejected_list_with_context(None, args)
    }

    /// Handles `GetRejectedList` for a request context that can prove the caller's channel and
    /// roles.
    pub fn handle_get_rejected_list_for_request(
        &self,
        context: &RequestContext,
        args: &[Variant],
    ) -> Result<Vec<Variant>, StatusCode> {
        self.handle_get_rejected_list_with_context(Some(context), args)
    }

    fn handle_get_rejected_list_with_context(
        &self,
        context: Option<&RequestContext>,
        args: &[Variant],
    ) -> Result<Vec<Variant>, StatusCode> {
        if !args.is_empty() {
            return Err(StatusCode::BadInvalidArgument);
        }

        authorize_get_rejected_list(context)?;

        let certificates = self
            .registry
            .rejected_certificates()
            .into_iter()
            .map(Variant::from)
            .collect::<Vec<_>>();
        let certificates = Array::new(VariantScalarTypeId::ByteString, certificates)
            .map_err(|_| StatusCode::BadUnexpectedError)?;

        Ok(vec![Variant::Array(Box::new(certificates))])
    }

    /// Handles `UpdateCertificate` and records certificate material for dynamic reload.
    pub fn handle_update_certificate(&self, args: &[Variant]) -> Result<Vec<Variant>, StatusCode> {
        self.handle_update_certificate_with_context(None, args)
    }

    /// Handles `UpdateCertificate` for a request context that can prove the caller's channel and
    /// roles.
    pub fn handle_update_certificate_for_request(
        &self,
        context: &RequestContext,
        args: &[Variant],
    ) -> Result<Vec<Variant>, StatusCode> {
        self.handle_update_certificate_with_context(Some(context), args)
    }

    fn handle_update_certificate_with_context(
        &self,
        context: Option<&RequestContext>,
        args: &[Variant],
    ) -> Result<Vec<Variant>, StatusCode> {
        authorize_encrypted_security_admin(context)?;

        if args.len() < 6 {
            return Err(StatusCode::BadArgumentsMissing);
        }

        let update = GdsCertificateUpdate {
            certificate_group_id: node_id_arg(args, 0)?,
            certificate_type_id: node_id_arg(args, 1)?,
            certificate: non_empty_byte_string_arg(args, 2)?,
            issuer_certificates: byte_string_array_arg(args, 3)?,
            private_key_format: string_arg(args, 4)?,
            private_key: byte_string_arg(args, 5)?,
        };
        validate_der_certificate(&update.certificate)?;
        validate_private_key(&update.private_key_format, &update.private_key)?;
        self.registry.record_certificate_update(update);

        Ok(vec![Variant::from(true)])
    }

    /// Handles `FinishSigningRequest` without a request context.
    pub fn handle_finish_signing_request(
        &self,
        args: &[Variant],
    ) -> Result<Vec<Variant>, StatusCode> {
        self.handle_finish_signing_request_with_context(None, args)
    }

    /// Handles the implementation-specific `FinishSigningRequest` helper for a request context
    /// that can prove the caller's encrypted channel and roles.
    pub fn handle_finish_signing_request_for_request(
        &self,
        context: &RequestContext,
        args: &[Variant],
    ) -> Result<Vec<Variant>, StatusCode> {
        self.handle_finish_signing_request_with_context(Some(context), args)
    }

    fn handle_finish_signing_request_with_context(
        &self,
        context: Option<&RequestContext>,
        args: &[Variant],
    ) -> Result<Vec<Variant>, StatusCode> {
        authorize_encrypted_security_admin(context)?;

        if args.len() < 2 {
            return Err(StatusCode::BadArgumentsMissing);
        }

        let application_id = node_id_arg(args, 0)?;
        let request_id = node_id_arg(args, 1)?;
        let request = self
            .registry
            .finished_signing_request(&application_id, &request_id)
            .ok_or(StatusCode::BadNotFound)?;

        Ok(vec![
            Variant::from(request.certificate),
            Variant::from(request.private_key),
        ])
    }
}

/// Returns the standard `GetRejectedList` method id from the task contract.
pub fn get_rejected_list_method_id() -> NodeId {
    NodeId::new(0, GET_REJECTED_LIST_METHOD_ID)
}

/// Returns the standard `UpdateCertificate` method id from the task contract.
pub fn update_certificate_method_id() -> NodeId {
    NodeId::new(0, UPDATE_CERTIFICATE_METHOD_ID)
}

/// Returns the implementation-specific `FinishSigningRequest` helper method id from the task
/// contract.
pub fn finish_signing_request_method_id() -> NodeId {
    update_certificate_method_id()
}

/// Registers GDS pull method callbacks on a simple node manager.
pub fn register_gds_pull_methods(node_manager: &SimpleNodeManager) -> GdsPullMethodRegistry {
    let registry = GdsPullMethodRegistry::default();
    register_gds_pull_methods_with_registry(node_manager, registry.clone());
    registry
}

/// Registers GDS pull method callbacks using the supplied registry.
pub fn register_gds_pull_methods_with_registry(
    node_manager: &SimpleNodeManager,
    registry: GdsPullMethodRegistry,
) {
    let handler = Arc::new(GdsPullMethodHandler::new(registry));

    let rejected_handler = handler.clone();
    node_manager
        .inner()
        .add_method_callback_with_context(get_rejected_list_method_id(), move |ctx, args| {
            rejected_handler.handle_get_rejected_list_for_request(ctx, args)
        });

    node_manager.inner().add_method_callback_with_context(
        update_certificate_method_id(),
        move |ctx, args| {
            if args.len() >= 6 {
                handler.handle_update_certificate_for_request(ctx, args)
            } else {
                handler.handle_finish_signing_request_for_request(ctx, args)
            }
        },
    );
}

fn authorize_get_rejected_list(context: Option<&RequestContext>) -> Result<(), StatusCode> {
    let Some(context) = context else {
        return Err(StatusCode::BadSecurityModeInsufficient);
    };

    if context.security_mode() == MessageSecurityMode::None {
        return Err(StatusCode::BadSecurityModeInsufficient);
    }

    if !context
        .user_roles()
        .contains(&WellKnownRole::SecurityAdmin.node_id())
    {
        return Err(StatusCode::BadUserAccessDenied);
    }

    Ok(())
}

fn authorize_encrypted_security_admin(context: Option<&RequestContext>) -> Result<(), StatusCode> {
    let Some(context) = context else {
        return Err(StatusCode::BadSecurityModeInsufficient);
    };

    if context.security_mode() != MessageSecurityMode::SignAndEncrypt {
        return Err(StatusCode::BadSecurityModeInsufficient);
    }

    if !context
        .user_roles()
        .contains(&WellKnownRole::SecurityAdmin.node_id())
    {
        return Err(StatusCode::BadUserAccessDenied);
    }

    Ok(())
}

fn validate_der_certificate(certificate: &ByteString) -> Result<(), StatusCode> {
    X509::from_byte_string(certificate)
        .map(|_| ())
        .map_err(|err| err.status())
}

fn validate_private_key(
    private_key_format: &str,
    private_key: &ByteString,
) -> Result<(), StatusCode> {
    if private_key.is_null_or_empty() {
        return if private_key_format.is_empty() {
            Ok(())
        } else {
            Err(StatusCode::BadNotSupported)
        };
    }

    match private_key_format {
        "PEM" => PrivateKey::from_pem(private_key.as_ref())
            .map(|_| ())
            .map_err(|_| StatusCode::BadNotSupported),
        "PFX" => Err(StatusCode::BadNotSupported),
        _ => Err(StatusCode::BadNotSupported),
    }
}

fn node_id_arg(args: &[Variant], index: usize) -> Result<NodeId, StatusCode> {
    match args.get(index) {
        Some(Variant::NodeId(node_id)) => Ok(node_id.as_ref().clone()),
        Some(_) => Err(StatusCode::BadTypeMismatch),
        None => Err(StatusCode::BadArgumentsMissing),
    }
}

fn byte_string_arg(args: &[Variant], index: usize) -> Result<ByteString, StatusCode> {
    match args.get(index) {
        Some(Variant::ByteString(value)) => Ok(value.clone()),
        Some(_) => Err(StatusCode::BadTypeMismatch),
        None => Err(StatusCode::BadArgumentsMissing),
    }
}

fn non_empty_byte_string_arg(args: &[Variant], index: usize) -> Result<ByteString, StatusCode> {
    let value = byte_string_arg(args, index)?;
    if value.is_null_or_empty() {
        Err(StatusCode::BadInvalidArgument)
    } else {
        Ok(value)
    }
}

fn byte_string_array_arg(args: &[Variant], index: usize) -> Result<Vec<ByteString>, StatusCode> {
    match args.get(index) {
        Some(Variant::Array(array)) if array.value_type == VariantScalarTypeId::ByteString => array
            .values
            .iter()
            .map(|value| match value {
                Variant::ByteString(value) => Ok(value.clone()),
                _ => Err(StatusCode::BadTypeMismatch),
            })
            .collect(),
        Some(Variant::Array(_)) | Some(_) => Err(StatusCode::BadTypeMismatch),
        None => Err(StatusCode::BadArgumentsMissing),
    }
}

fn string_arg(args: &[Variant], index: usize) -> Result<String, StatusCode> {
    match args.get(index) {
        Some(Variant::String(value)) => Ok(value.as_ref().to_owned()),
        Some(_) => Err(StatusCode::BadTypeMismatch),
        None => Err(StatusCode::BadArgumentsMissing),
    }
}
