extra_header: |
  // OPCUA for Rust
  // SPDX-License-Identifier: MPL-2.0
  // Copyright (C) 2017-2024 Adam Lock, Einar Omang
targets:
  - type: types
    file: opc.ua.fx.data.nodeset2.xml
    output_dir: src/generated/types
    enums_single_file: true
    structs_single_file: true
    types_import_map:
      KeyValuePair:
        path: "opcua::types::key_value_pair"
        base_type: "ExtensionObject"
        add_to_type_loader: false
      ConfigurationVersionDataType:
        path: "opcua::types::configuration_version_data_type"
        base_type: "ExtensionObject"
        add_to_type_loader: false
      PubSubConfiguration2DataType:
        path: "opcua::types::pub_sub_configuration_2_data_type"
        base_type: "ExtensionObject"
        add_to_type_loader: false
      PubSubConfigurationRefDataType:
        path: "opcua::types::pub_sub_configuration_ref_data_type"
        base_type: "ExtensionObject"
        add_to_type_loader: false
      PubSubConfigurationValueDataType:
        path: "opcua::types::pub_sub_configuration_value_data_type"
        base_type: "ExtensionObject"
        add_to_type_loader: false
      PortableQualifiedName:
        path: "opcua::types::portable_qualified_name"
        base_type: "ExtensionObject"
        add_to_type_loader: false
      ConnectionEndpointDefinitionDataType:
        path: "crate::connection_endpoint_definition_data_type"
        has_default: true
        base_type: "ExtensionObject"
        add_to_type_loader: true
      PubSubConnectionEndpointModeEnum:
        path: "crate::pub_sub_connection_endpoint_mode_enum"
        has_default: true
    extra_header: |
      #![allow(non_camel_case_types)]
      #![allow(clippy::upper_case_acronyms)]
      #[allow(unused)]
      mod opcua { pub(super) use opcua_types as types; }

sources:
  - schema
  - ../schemas/1.05/Opc.Ua.Types.xsd
  - ../schemas/1.05/Opc.Ua.NodeSet2.xml
